Vagrant.configure("2") do |config|
  config.vm.box = "jasonc/centos7"
  config.vm.hostname = "03-local-users"
  config.vm.provision "shell",
   path: "01-naming-permissions-variables-builtins.sh"
end
